### ISSUE TITLE
The actual camera settings are not saved in the preset

### ISSUE THREAD

**Issue by tkolenbrander** [TH3steven/Context-TFP#15]
Currently there is no communication with any camera's so we can't save the actual preset settings when creating or editing a preset. When it is possible to retrieve these settings, they should be saved.

**Comment by bvobart** [comment]
Or we should find a good way to mock this.

**Comment by tkolenbrander** [comment]
@bvobart Will this be possible with the mock class you and @Ettatabe created? In order to get the actual settings, I need to read some of the camera settings.

**Comment by bvobart** [comment]
@tkolenbrander Yes, you can now add a CameraConnection object to a camera, which can either be a LiveCameraConnection or MockedCameraConnection object for now. Let me know when you're going to work on implementing the connection to the cameras, I'll help you out.
