### ISSUE TITLE
No scrolling through shotbox

### ISSUE THREAD

**Issue by TimYuenior** [TH3steven/Context-TFP#20]
In the UI of the preview screen there need to be arrows or something else, so the user can scroll through the box of shots below the main screen view. Currently, to get to shots that the user does not directly see, (s)he must use the choicebox in the top left.

**Comment by tkolenbrander** [comment]
@TimYuenior You already fixed this right?

**Comment by TimYuenior** [comment]
Yes, that's right. I'll close the issue. Thanks for the reminder.
