### ISSUE TITLE
Saved xml file is kept open in program

### ISSUE THREAD

**Issue by stevenmeijer** [TH3steven/Context-TFP#30]
Saving a script will keep the saved file opened in the program, making users unable to delete it without closing the program.

**Comment by bvobart** [comment]
@TH3steven I've taken a good look through the code and through the internet and it seems that changing the `FileWriter` used in SaveScript to a `FileOutputStream` does the job of fixing this issue. I've pushed this fix to the `savefileFix` branch, could you take a look to see if this actually fixed your problem?

**Comment by stevenmeijer** [comment]
@bvobart Yup this has been fixed
