### ISSUE TITLE
Saving a script with no preset results in Nullpointer

### ISSUE THREAD

**Issue by stevenmeijer** [TH3steven/Context-TFP#51]
Saving a script without a preset, which is possible since 287b8d7792fb3436f8c3b02cd867981fd5d5c859, creates a NullPointer exception both when saving and loading, and failes to load entirely. This is because the backend can't handle a null preset yet.

**Comment by bvobart** [comment]
@TH3steven This problem should now be fixed in the `savefileFix` branch. I've updated LoadScriptTest and SaveScriptTest to show this. Can you confirm?

**Comment by stevenmeijer** [comment]
@bvobart Some quick testing shows that this indeed allows the preset to be null and still be saved and loaded without throwing errors. I will add None as a preset option again
